version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orderservice:
    build:
      context: ./orderservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8082:8080"

volumes:
  postgres_data: